HEADERS += \
    $$PWD/TermRender.h \
    $$PWD/TermViewport.h \
    $$PWD/TermWidget.h \
    $$PWD/buffer/AttrRow.h \
    $$PWD/buffer/AttrRowCell.h \
    $$PWD/buffer/CharRow.h \
    $$PWD/buffer/CharRowCell.h \
    $$PWD/buffer/Cursor.h \
    $$PWD/buffer/IRenderTarget.h \
    $$PWD/buffer/Row.h \
    $$PWD/buffer/TextBuffer.h \
    $$PWD/buffer/TextColor.h \
    $$PWD/buffer/TextStyle.h \
    $$PWD/buffer/Types.h \
    $$PWD/buffer/UAttrCharCell.h \
    $$PWD/buffer/UChar.h \
    $$PWD/buffer/Viewport.h \
    $$PWD/config/TermConfig.h \
    $$PWD/parser/ASCII.h \
    $$PWD/parser/DispatchTypes.h \
    $$PWD/parser/IStateMachineEngine.h \
    $$PWD/parser/ITermDispatch.h \
    $$PWD/parser/ITerminalOutputConnection.h \
    $$PWD/parser/OutputStateMachineEngine.h \
    $$PWD/parser/StateMachine.h \
    $$PWD/parser/StateMachineEngineTest.h \
    $$PWD/parser/Til.h \
    $$PWD/render/IRenderData.h \
    $$PWD/terminal/ITerminal.h \
    $$PWD/terminal/ITerminalControl.h \
    $$PWD/terminal/ITerminalInput.h \
    $$PWD/terminal/TermDispatch.h \
    $$PWD/terminal/Terminal.h \
    $$PWD/terminal/TerminalDispatch.h \
    $$PWD/terminal/TerminalMode.h \
    $$PWD/tracing/OutputStateMachineEngineTracing.h \
    $$PWD/tracing/StateMachineTracing.h \
    $$PWD/tracing/TermDispatchTracing.h

SOURCES += \
    $$PWD/TermRender.cpp \
    $$PWD/TermViewport.cpp \
    $$PWD/TermWidget.cpp \
    $$PWD/buffer/AttrRow.cpp \
    $$PWD/buffer/AttrRowCell.cpp \
    $$PWD/buffer/CharRow.cpp \
    $$PWD/buffer/CharRowCell.cpp \
    $$PWD/buffer/Cursor.cpp \
    $$PWD/buffer/Row.cpp \
    $$PWD/buffer/TextBuffer.cpp \
    $$PWD/buffer/TextColor.cpp \
    $$PWD/buffer/UAttrCharCell.cpp \
    $$PWD/buffer/UChar.cpp \
    $$PWD/buffer/Viewport.cpp \
    $$PWD/config/TermConfig.cpp \
    $$PWD/parser/OutputStateMachineEngine.cpp \
    $$PWD/parser/StateMachine.cpp \
    $$PWD/parser/StateMachineEngineTest.cpp \
    $$PWD/terminal/ITerminalInput.cpp \
    $$PWD/terminal/Terminal.cpp \
    $$PWD/terminal/TerminalDispatch.cpp \
    $$PWD/tracing/OutputStateMachineEngineTracing.cpp \
    $$PWD/tracing/StateMachineTracing.cpp \
    $$PWD/tracing/TermDispatchTracing.cpp
